;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(markdown-exdent-or-delete
                               end-of-buffer
                               downcase-region
                               wdired-next-line
                               ignore
                               kmacro-start-macro-or-insert-counter
                               python-indent-dedent-line-backspace
                               org-cycle
                               c-electric-slash
                               js2-beginning-of-line
                               execute-extended-command
                               dabbrev-expand
                               js2-end-of-line
                               sgml-slash
                               yas/expand
                               kill-region
                               forward-paragraph
                               c-electric-semi&comma
                               c-electric-paren
                               org-beginning-of-line
                               org-delete-char
                               org-delete-backward-char
                               org-end-of-line
                               quoted-insert
                               org-yank
                               org-self-insert-command))

(setq mc/cmds-to-run-once '(dired-sort-toggle-or-edit
                            dired-previous-line
                            dired-unmark-backward
                            mouse-set-region
                            mouse-set-point
                            mouse-drag-region
                            mwheel-scroll
                            c-electric-backspace))

                            
                               